### ISSUE TITLE
Items occasionally lose texture.

### ISSUE THREAD

**Issue by Lethann** [Nuchaz/BiblioCraft#438] opened 2017-03-29 22:06 UTC
Bibliocraft 2.2.1
Minecraft 1.10.2
Forge 12.18.3.2254

Custom modpack on private server

At seemingly random times I'll log into our server and find certain items not rendering properly. First I noticed the oak toolshelves appearing as oak plank blocks. I was able to interact with them fine and get my tools out of it but they were not appearing so had to pull them down. Next time I logged in they were fine and was able to put them back up.

Next my framed desk appeared with the pink and black 'missing texture'. Again I was able to interact with it. This time I just left it alone and the next time I logged in it was fine.

Twice now I've had the oak fancy signs lose their texture. At least this time the text and items are showing up, the first time it was just the plank texture on the wall and unreadable.

![2017-03-29_16 58 17](https://cloud.githubusercontent.com/assets/25929754/24478747/ac20c40c-14a1-11e7-8eb4-46a4ecbbce26.png)

**Comment by Lethann** [comment] 2017-03-29 22:12
Ok I just walked into another building and saw this: 

![2017-03-29_17 09 58](https://cloud.githubusercontent.com/assets/25929754/24478987/d2d013e0-14a2-11e7-904d-7c63d2cf2936.png)


- Potion Shelves invisable
- far left block is plain sakura planks
- middle missing texture is typesetting table
- right block is printing press

Then here is my armor stand

![2017-03-29_17 11 49](https://cloud.githubusercontent.com/assets/25929754/24478996/d9594e8e-14a2-11e7-9a23-b7cf59086799.png)

**Comment by WesCook** [comment] 2017-04-03 13:18
My Framed Chests are occasionally missing their models/textures when I load the game.

![2017-04-03_07 17 49](https://cloud.githubusercontent.com/assets/792101/24610954/5c076aba-1835-11e7-8b7c-cbd685472d59.png)

I'm unsure if it's caused by a conflict or not, as it seems erratic.

**Comment by Ravin890** [comment] 2017-04-04 17:00
Bibliocraft is still kinda iffy. Nuchaz hasn't had time to fix the rendering issue yet, and it has been reported numerous times.

**Comment by Nuchaz** [comment] 2017-05-13 10:06
related to #418  I think I know what is happening and I have a fix planned, so hopefully that will take care of it. I am closing this issue to consolidate.

**Closed by Nuchaz** 2017-05-13 10:06 UTC

**Comment by AgentCPU0** [comment] 2021-02-06 02:58
This is still an issue. Please fix it
