### ISSUE TITLE
(1.12.2) "The game crashed whilst tesselating block model"

### ISSUE THREAD

**Issue by beanaboston** [Nuchaz/BiblioCraft#511] opened 2017-10-14 14:19 UTC
Clipboard is causing a crash. It works fine when I disable the mod, then upon enabling the mod it starts crashing again. Disabling the clipboard in config stops the crash, when I enable it again it starts crashing again. I am using version 2.4.3.
Crash report: https://pastebin.com/m3TgByPc
Just thought I would let you know, since all the other crash reports similar to this were in a previous version it seems.

**Comment by Milii20** [comment] 2017-10-16 16:14
i had the same crash, but i can add a tiny bit more information:
My crash happen with the clipboard on the wall, not in your hand.
I have an amd rx 480, and my fiance has a nvidia gtx 450, my client crashed when i was looking at the clipboard, but her client didn't crash at all, in fact, she was able to use the  clipboard.

**Comment by joakime** [comment] 2018-02-16 12:40
Possible duplicate of #490 ?

**Comment by Nuchaz** [comment] 2018-05-23 01:52
I think I figured out a fix for this. Expect a fix in the next release, which will be v2.4.4 for MC 1.12.2. I am closing this issue for now. Let me know if anyone still has issues after the next release.

**Closed by Nuchaz** 2018-05-23 01:52 UTC
