### ISSUE TITLE
Crash with Botania's Wand of the Forest in a Bibliocraft framed chest

### ISSUE THREAD

**Issue by Febilian** [Nuchaz/BiblioCraft#316] opened 2015-09-10 20:24 UTC
https://paste.ee/p/b2soJ

I was trying to replace an item in the framed chest with a Wand of the Forest from Botania from my inventory, and my client crashed as soon as the wand was put in the chest. The item I was replacing in the chest was a single magenta petal from Botania, and I was trying to replace it with a Wand of the Forest, also from Botania. I'm going to guess based on what I can make of the error that this crash had something to do with the chest attempting to dynamically render the label and failing for some reason.

Maybe it freaked out because I was trying to replace the item that it was trying to display in the label already(I didn't have much in that half of the chest, everything there was either unstackable or there was only one of them)? Or maybe it just doesn't like the wand of the forest or similar items? The wand does change its appearance/texture based on what color petals it was crafted with while still using the same ID/metadata. Don't know if that's relevant, though, I just thought I should bring it up just in case it IS a factor.

This appears to have made the area around the chest crash the client of anyone whose game tries to render the chest label. Using the forge config on my private server for removing erroring tile entities doesn't fix the issue, because it's not causing an error on the server - it's a clientside crash. Do I have to remove the chest in question in another way using an external editor because of this? Even if this can be fixed, any help for a workaround in the meantime would be appreciated.

**Comment by Nuchaz** [comment] 2015-09-10 20:31
Thanks for the report. I'll look into this. It looks like it happens when I try to get the texture resource for the item. It must be because of the dynamic rendering setup of the botania item. I'll try to figure out what it is an get an update out when I get some time. Likely this weekend at the earliest.

To recover the world, the easiest thing to do would be to editing the BiblioCraft config on the clientside and set "B:DisableRenderers=false" to true. That will disable all BiblioCraft renderers so all the BiblioCraft block will appear invisible in the world, but you should still be able to access the inventory and remove offending items or break the block.

**Comment by Febilian** [comment] 2015-09-10 20:37
Alright, thank you for the response, and glad I could bring this to light! I hope you can resolve the issue. I will try the config option, seems like that should work.

**Comment by Nuchaz** [comment] 2015-09-13 07:43
I just posted BiblioCraft v1.11.1 which has a fix for this in it.

**Comment by CandiceJoy** [comment] 2015-09-18 01:49
I still get this error as of v1.11.1 http://pastebin.com/LvWwVgsS

Also, disabling rendering doesn't stop the crash.

**Comment by Nuchaz** [comment] 2015-09-19 08:17
I reopened the issue. I will investigate further. I thought I had it fixed, but apparently something is still going on.

**Comment by Nonsanity** [comment] 2015-09-20 02:51
I can confirm this bug. I and others on my server are experiencing the same crash when looking towards a framed chest that just had its contents changed. v1.11.1

**Comment by Nonsanity** [comment] 2015-09-20 02:56
The config change DOES work, but you have to do it on the client side, where the crash is. Changing it on the server doesn't help.

**Comment by Nuchaz** [comment] 2015-09-20 04:49
I think I found the issue on my end, I should be able to patch it up no problems. Expect a fix in 1.12.0 whenever I get it done

**Closed** 2015-09-20 21:06 UTC
