### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by LuxusDarkangel** [Nuchaz/BiblioCraft#308] opened 2015-08-07 06:53 UTC
I don't know how to reproduce it, just started spamming this error in console and players weren't able to join the server for hours until it crashed (i was sleeping, so i couldn't stop the server)
Crash report: http://pastebin.com/YBzDCRh3

**Comment by Nuchaz** [comment] 2015-08-07 19:41
Hmm, something went wrong when someone dropped something. I have an item toss event that runs when someone drops something as one of the extra measures I took to prevent item duping with the slotted book. 

I'll see what I can try to do to prevent this. I can't seem to reproduce it, but maybe I can put in an extra check or 2 based on what I am seeing in the crash log. If you come across a way to reproduce it, let me know.

**Comment by Nentify** [comment] 2015-08-09 22:19
I'm getting this too and after this error occurs (third time now) the world becomes sort of corrupted. IDs change completely and I have to rollback. :/

**Comment by Nuchaz** [comment] 2015-08-10 00:22
I think I've managed to reproduce it. It seems to happen if you drop (throw on the ground) a bibliocraft item like the slotted book (also atlas, big book, recipe book, clipboard, redstone book, and waypoint compass) when you're in another container like a chest or something.

I think I have an idea on a fix too.  I'll try to get one out as soon as I can.

**Comment by LuxusDarkangel** [comment] 2015-08-10 15:06
Yes, that causes this problem. Also, i don't know how the old slotted book dupe bug worked, but when my server crashed i decompiled your mod to see what was the purpose of EventItemToss and try to give you a way to reproduce it. After a look at the code, i started trying to crash the server using the guis from atlas, big book, etc. Obviously i couldn't, because the problem is not the gui, but while i was trying with the slotted book using a stack of Quicksand, it suddenly dropped another stack to the ground while i was holding one on my hand. Again i tried to reproduce it and i couldn't, but there's still a way to duplicate items, just to let you know.

**Comment by Nentify** [comment] 2015-08-10 16:14
Do you know how long it'll be before a fix is it? Hours/days?

**Comment by Nuchaz** [comment] 2015-08-10 16:34
dang, I thought I had the dupe bugs fixed. Thanks for the report. I'll add it back to my list to reopen investigations on that. I'll try to get a fix out for the crash first though. I'm tentatively planning to do a release tonight after I get home. So, I am planning for hours, not days.

**Comment by LuxusDarkangel** [comment] 2015-08-10 19:48
If i can help you in anyway, let me know.

**Comment by Nentify** [comment] 2015-08-10 22:10
Is this coming soon? Don't mean to bug >.< Just don't want to risk leaving my server up overnight and have to roll back again.

**Comment by LuxusDarkangel** [comment] 2015-08-10 22:21
My server crashed twice, and this bug dont cause world corruption. Maybe it occured during world save and corrupted your level.dat, so your server created a new one, with new ids.
Either you can temporarily ban these items using ItemRestrict if you're Kcauldron.

**Comment by Nuchaz** [comment] 2015-08-11 00:35
going to release very soon. I just got home not long ago. I am working on getting stuff around to do a release right now. It should be up within the hour if I don't run into any problems along the way.

**Comment by Nuchaz** [comment] 2015-08-11 01:01
fixed in v1.10.6. Just finished posting the update on the website and on curseforge.

**Closed by Nuchaz** 2015-08-11 01:01 UTC
Labels: bug
