### ISSUE TITLE
Server Crashes when player joins

### ISSUE THREAD

**Issue by jordyvl** [Nuchaz/BiblioCraft#282] opened 2015-04-28 13:12 UTC
I am sorry if someone posted about this before but my server crashes and i think this mod causes the crash. Can you please tell me how i can solve this problem?
http://pastebin.com/Cxk59wR5
This is the crash log the server crashes as soon as any player tries to join
The server was working perfectly but after a few hours it just stopped working and i can not see why as i don't understand what the crashlog is telling me.

**Comment by jordyvl** [comment] 2015-04-28 13:14
Before the server crashed i copied some books using the printing press when i walked a few blocks away from the machine the whole server crashed and shut it self down this is the log of that crash http://pastebin.com/W2RQhGmH

**Comment by Nuchaz** [comment] 2015-04-28 20:32
Hmm, it looks like it is the printing press that is crashing when it tries to figure out what kind of book it is printing. What type of book did you copy /  print? Vanilla writing book, big book, or recipe book?

**Comment by jordyvl** [comment] 2015-04-29 05:20
A vanillia writing book






<div>-------- Oorspronkelijk bericht --------</div><div>Van: Nuchaz <notifications@github.com> </div><div>Datum:28-04-2015  22:32  (GMT+01:00) </div><div>Aan: Nuchaz/BiblioCraft <BiblioCraft@noreply.github.com> </div><div>Cc: Jordy van laerhoven <jordyvl1@me.com> </div><div>Onderwerp: Re: [BiblioCraft] Server Crashes when player joins (#282) </div><div>
</div>Hmm, it looks like it is the printing press that is crashing when it tries to figure out what kind of book it is printing. What type of book did you copy / print? Vanilla writing book, big book, or recipe book?

**Comment by Nuchaz** [comment] 2015-04-29 21:08
I can't seem to reproduce the issue, so maybe the book data got corrupted somehow. The books are saved to separate files and that separate file is what the printing press is trying to use. Go into your world folder on your server and go into the "books" folder and find the file of whatever book you put on the printing press. It will be listed called "playerName, bookTitle" with no extension. These are actually text files and you should be able to open it in any basic text editor. You can either open the file and check the formating. The first line will be the book title, the second line will be the author name, the 3rd line should say private or public and the 4th line should start with "#pgx0" which indicates the start of the first page. 

If you can't open the file or it is empty, that will be indication it got corrupted and you will need to delete it. Your vanilla written book will be unaffected so you should be able to try re-saving the book in the typesetting table and going from there. 

If the printing press tries to print a book from a plate that isn't in that books folder, it should just throw a warning in your server log every attempt to print, but the game will run fine.

**Comment by jordyvl** [comment] 2015-04-30 19:21
It worked thank you





<div>-------- Oorspronkelijk bericht --------</div><div>Van: Nuchaz <notifications@github.com> </div><div>Datum:29-04-2015  23:08  (GMT+01:00) </div><div>Aan: Nuchaz/BiblioCraft <BiblioCraft@noreply.github.com> </div><div>Cc: Jordy van laerhoven <jordyvl1@me.com> </div><div>Onderwerp: Re: [BiblioCraft] Server Crashes when player joins (#282) </div><div>
</div>I can't seem to reproduce the issue, so maybe the book data got corrupted somehow. The books are saved to separate files and that separate file is what the printing press is trying to use. Go into your world folder on your server and go into the "books" folder and find the file of whatever book you put on the printing press. It will be listed called "playerName, bookTitle" with no extension. These are actually text files and you should be able to open it in any basic text editor. You can either open the file and check the formating. The first line will be the book title, the second line will be the author name, the 3rd line should say private or public and the 4th line should start with "#pgx0" which indicates the start of the first page.

If you can't open the file or it is empty, that will be indication it got corrupted and you will need to delete it. Your vanilla written book will be unaffected so you should be able to try re-saving the book in the typesetting table and going from there.

If the printing press tries to print a book from a plate that isn't in that books folder, it should just throw a warning in your server log every attempt to print, but the game will run fine.

**Closed** 2016-09-06 11:37 UTC
