### ISSUE TITLE
 [1.7.10] Another Dupe

### ISSUE THREAD

**Issue by jon100456** [Nuchaz/BiblioCraft#422] opened 2017-03-03 23:20 UTC
Hey! there another duplication bug for Fancy workbench here a video on how to do it
https://www.youtube.com/watch?v=qJ0PA28otYw
please patch this

**Comment by Nuchaz** [comment] 2017-05-15 08:48
duplicate of issue #390  Working on fixing this now.

**Closed by Nuchaz** 2017-05-15 08:48 UTC
Labels: bug
