### ISSUE TITLE
[1.10.2] Crash tesselating block model (Sign) 

### ISSUE THREAD

**Issue by Eufranio** [Nuchaz/BiblioCraft#455] opened 2017-05-24 17:44 UTC
This crash happened when I placed a BiblioCraft sign and reconnected to the server: https://hastebin.com/sukelucuzu

**Comment by Nuchaz** [comment] 2017-05-24 19:50
related to #451 and #453 There seems to be an issue related to optifine. I am stilll trying to reproduce and diagnose locally.

**Comment by Eufranio** [comment] 2017-05-24 20:12
We're all running FoamFix, are you in your test?

**Comment by Nuchaz** [comment] 2017-05-24 21:29
Good catch, no I am not. I will grab that and experiment with it.

**Comment by liquidcobalt47** [comment] 2017-05-26 10:46
Getting the same/similar error on Toolracks w/o Optifine. Sometimes it crashes 3 seconds into the game sometimes you can run around longer. https://hastebin.com/ujaligiloy.pas

**Comment by VT-14** [comment] 2017-05-26 15:13
I'm getting a very similar crash in 1.11.2.  In Survival Single Player, I easily went 5+ hours without any problems.  About 30 seconds after finishing a Tier IV Woot Farm (I don't think it's related), I got this crash:
https://gist.github.com/VT-14/2e187df71cbbea309367da2dca026796

I was then unable to log back in with pretty much the same crash report.  I never use Optifine, and I disabled FoamFix.  Still crashing on startup with the following crash report.
Crash: https://gist.github.com/VT-14/d9d052080204f586f5aea9a9323d5ec7
FML Log: https://gist.github.com/VT-14/1d73b2cc64df858eb068e5957b8716d5

Minecraft: 1.11.2
Forge: 13.20.0.2296
Bibliocraft: 2.3.0

**Comment by Nuchaz** [comment] 2017-05-28 01:12
I think I have an idea as to what might be causing these crashes. There is two things that I think could come up null that I am going to check and I also am putting in some extra try/catch statements for null-pointer exceptions so if the crash happens again, hopefully I will get a little more information as to exactly where its coming from. Hopefully I am right about what is causing the crash and have it fixed. 

I will try to get a release out maybe tomorrow (Sunday may 28) with the fixes and you guys will have to let me know if that takes care of it. For whatever reason, I haven't actually experienced the crash so I've been just thinking through my code logically and trying to find any weak spots.

**Comment by Ricdan** [comment] 2017-05-28 10:58
Hi,
Having too a tesselating crash on our modded survival server.
Here's the crash report.
https://pastebin.com/eVxtG2RD
I tryed to delete the blocks targeted in the crash report with mcedit, but it didn't resolve the problem...
I hop it can help you to resolve that bug.

**Comment by Nuchaz** [comment] 2017-05-29 01:34
I just released an update that hopefully has a fix for this. If not, I added some additional try/catch stuff that will hopefully help me figure out what is happening. Post some crash logs if you still crash with the newest versions. I made the changes to all three new versions covering Minecraft 1.9.4, 1.10.2 and 1.11.2

**Comment by VT-14** [comment] 2017-05-29 03:11
Well, I loaded up a backup that has this problem, and it crashed.  Bibliocraft 2.3.1 on Minecraft 1.11.2.  Forge 2296, which I don't think is completely up to date.

Crash: https://gist.github.com/VT-14/aea28d16458040ef86a9235cff2293aa
Log: https://gist.github.com/VT-14/d17cb57692b142e2151591f70534f5a8

**Comment by Ricdan** [comment] 2017-05-29 07:20
Unfortunately, still crashing on 1.11.2.
Here's the crash report : https://pastebin.com/rcr6xTzF

**Comment by ziocho** [comment] 2017-05-29 10:13
Also having this crash with a bookcase on 1.11.2, Bibliocraft v2.3.1

Crash Report: http://puu.sh/w4p22/0b1a059fce.txt

**Comment by dualmoon** [comment] 2017-06-02 16:13
[crash-2017-06-02_09.41.44-client.txt](https://github.com/Nuchaz/BiblioCraft/files/1048254/crash-2017-06-02_09.41.44-client.txt)
[crash-2017-06-02_08.07.27-client.txt](https://github.com/Nuchaz/BiblioCraft/files/1048255/crash-2017-06-02_08.07.27-client.txt)

Attached are a couple of crash logs from the newest update of Bibliocraft on 1.10.2.

**Comment by Nuchaz** [comment] 2017-06-03 20:05
thanks for the additional crash logs, I am still trying to figure this one out. The place it crashed has moved since the last update, so I did something. I still haven't been able to reproduce the crash on my computer yet which is why it is so hard to fix.

**Comment by dualmoon** [comment] 2017-06-03 20:07
@Nuchaz if it would help I can give you a copy of my world and a link to my pack. Theoretically you could reproduce it that way.

**Comment by Nuchaz** [comment] 2017-06-03 20:15
@dualmoon  Actually yeah, that could be helpful. If I could get a hold of a world that is crashing for sure and I can reproduce the crash, I can work to get it figured out much easier.

**Comment by dualmoon** [comment] 2017-06-03 20:40
@Nuchaz 

https://cdn.neko.lgbt/mc/world-bibliocraft-crash-06032017.zip

This is an SMP world so not sure what all you need, but here's some stuff:

config folder: https://cdn.neko.lgbt/mc/config-bibliocraft-crash-06032017.zip
mods folder: https://cdn.neko.lgbt/mc/mods-bibliocraft-crash-06032017.zip
server runs forge 2281

Finally, client mod pack (I use MultiMC): https://cdn.neko.lgbt/mc/World%20In%20Chaos%20v0.29.zip
v0.29 of the pack runs Bibliocraft 2.2.3

**Comment by Nuchaz** [comment] 2017-06-04 20:59
Thanks, I've been experimenting with it a bit and at first, it was crashing on load. I removed enderIO and it loaded fine after that. I hadn't experienced an crashes yet. I learned some things about some mods and found a couple mods I like and am adding to my own world though after checking out your world. It was fun exploring. ;) 

I am still experimenting, but an issue was brought up today on here, #465 which said the crash was occurring when optifines has connected textures enabled. I am about to experiment with that real soon.

**Comment by dualmoon** [comment] 2017-06-04 22:40
Glad you had fun! Let me know if there's anything else I can help with.

**Comment by Nuchaz** [comment] 2017-06-07 01:08
I think I've got the root of the problem figured out and I am working on a fix, I'll update this thread and others as soon as I've got a fix worked out. Hopefully I can have an update out by this weekend at the latest

**Comment by Nuchaz** [comment] 2017-06-08 00:46
I have a fix out for this. I rolled the fix into BiblioCraft v2.1.4 for MC 1.9.4, BiblioCraft v2.2.4 for MC 1.10.2 and BiblioCraft v2.3.2 for MC 1.11.2. Closing the issue. You should be able to load worlds that have been permanently crashed by this bug.  Let me know if you experience anything weird.

**Closed by Nuchaz** 2017-06-08 00:46 UTC
Labels: bug
